import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const core = (await fs.readFile(path.join(root, 'core.js'), 'utf8')).replace(/^export /gm, '');
const entry = await fs.readFile(path.join(root, 'client-entry.js'), 'utf8');
if (!entry.includes('/* SHARED_CORE */')) throw new Error('Missing shared core marker.');
await fs.writeFile(path.join(root, 'client.js'), '// Generated by tools/build-client.mjs; edit client-entry.js and core.js.\n' + entry.replace('/* SHARED_CORE */', core));
console.log('Built browser client.');
